# Generated by Django 4.1.2 on 2022-11-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_author_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
