# Generated by Django 4.1.2 on 2022-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.CharField(choices=[('all', 'ALL'), ('cs', 'CS'), ('it', 'IT'), ('tc', 'ETC'), ('ei', 'EI'), ('cv', 'CIVIL'), ('me', 'MECH')], default='all', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.CharField(choices=[('all', 'ALL'), ('1', 'I Year'), ('2', 'II Year'), ('3', 'III Year'), ('4', 'IV Year')], default='all', max_length=6),
        ),
    ]
