# Generated by Django 4.1.2 on 2022-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
